#!/usr/bin/env sh
set -eu

API_BASE_URL="${SPRITZ_API_BASE_URL:-}"
OWNER_ID="${SPRITZ_UI_OWNER_ID:-}"
AUTH_MODE="${SPRITZ_UI_AUTH_MODE:-}"
AUTH_TOKEN_STORAGE="${SPRITZ_UI_AUTH_TOKEN_STORAGE:-}"
AUTH_TOKEN_STORAGE_KEYS="${SPRITZ_UI_AUTH_TOKEN_STORAGE_KEYS:-}"
AUTH_BEARER_TOKEN_PARAM="${SPRITZ_UI_AUTH_BEARER_TOKEN_PARAM:-}"
AUTH_LOGIN_URL="${SPRITZ_UI_AUTH_LOGIN_URL:-}"
AUTH_RETURN_TO_MODE="${SPRITZ_UI_AUTH_RETURN_TO_MODE:-}"
AUTH_RETURN_TO_PARAM="${SPRITZ_UI_AUTH_RETURN_TO_PARAM:-}"
AUTH_REDIRECT_ON_UNAUTHORIZED="${SPRITZ_UI_AUTH_REDIRECT_ON_UNAUTHORIZED:-}"
AUTH_REFRESH_ENABLED="${SPRITZ_UI_AUTH_REFRESH_ENABLED:-}"
AUTH_REFRESH_URL="${SPRITZ_UI_AUTH_REFRESH_URL:-}"
AUTH_REFRESH_METHOD="${SPRITZ_UI_AUTH_REFRESH_METHOD:-}"
AUTH_REFRESH_CREDENTIALS="${SPRITZ_UI_AUTH_REFRESH_CREDENTIALS:-}"
AUTH_REFRESH_TOKEN_STORAGE_KEYS="${SPRITZ_UI_AUTH_REFRESH_TOKEN_STORAGE_KEYS:-}"
AUTH_REFRESH_TIMEOUT_MS="${SPRITZ_UI_AUTH_REFRESH_TIMEOUT_MS:-}"
AUTH_REFRESH_COOLDOWN_MS="${SPRITZ_UI_AUTH_REFRESH_COOLDOWN_MS:-}"
AUTH_REFRESH_HEADERS="${SPRITZ_UI_AUTH_REFRESH_HEADERS:-}"
AUTH_PRESETS="${SPRITZ_UI_PRESETS:-}"
DEFAULT_REPO_URL="${SPRITZ_UI_DEFAULT_REPO_URL:-}"
DEFAULT_REPO_DIR="${SPRITZ_UI_DEFAULT_REPO_DIR:-}"
DEFAULT_REPO_BRANCH="${SPRITZ_UI_DEFAULT_REPO_BRANCH:-}"
HIDE_REPO_INPUTS="${SPRITZ_UI_HIDE_REPO_INPUTS:-}"
ASSET_VERSION="${SPRITZ_UI_ASSET_VERSION:-}"

if [ -z "$API_BASE_URL" ]; then
  API_BASE_URL="/api"
fi
if [ -z "$ASSET_VERSION" ]; then
  ASSET_VERSION="$(date +%s)"
fi

escape_sed() {
  printf '%s' "$1" | sed -e 's/[\\/&|]/\\&/g'
}

API_BASE_URL_ESCAPED="$(escape_sed "$API_BASE_URL")"
OWNER_ID_ESCAPED="$(escape_sed "$OWNER_ID")"
AUTH_MODE_ESCAPED="$(escape_sed "$AUTH_MODE")"
AUTH_TOKEN_STORAGE_ESCAPED="$(escape_sed "$AUTH_TOKEN_STORAGE")"
AUTH_TOKEN_STORAGE_KEYS_ESCAPED="$(escape_sed "$AUTH_TOKEN_STORAGE_KEYS")"
AUTH_BEARER_TOKEN_PARAM_ESCAPED="$(escape_sed "$AUTH_BEARER_TOKEN_PARAM")"
AUTH_LOGIN_URL_ESCAPED="$(escape_sed "$AUTH_LOGIN_URL")"
AUTH_RETURN_TO_MODE_ESCAPED="$(escape_sed "$AUTH_RETURN_TO_MODE")"
AUTH_RETURN_TO_PARAM_ESCAPED="$(escape_sed "$AUTH_RETURN_TO_PARAM")"
AUTH_REDIRECT_ON_UNAUTHORIZED_ESCAPED="$(escape_sed "$AUTH_REDIRECT_ON_UNAUTHORIZED")"
AUTH_REFRESH_ENABLED_ESCAPED="$(escape_sed "$AUTH_REFRESH_ENABLED")"
AUTH_REFRESH_URL_ESCAPED="$(escape_sed "$AUTH_REFRESH_URL")"
AUTH_REFRESH_METHOD_ESCAPED="$(escape_sed "$AUTH_REFRESH_METHOD")"
AUTH_REFRESH_CREDENTIALS_ESCAPED="$(escape_sed "$AUTH_REFRESH_CREDENTIALS")"
AUTH_REFRESH_TOKEN_STORAGE_KEYS_ESCAPED="$(escape_sed "$AUTH_REFRESH_TOKEN_STORAGE_KEYS")"
AUTH_REFRESH_TIMEOUT_MS_ESCAPED="$(escape_sed "$AUTH_REFRESH_TIMEOUT_MS")"
AUTH_REFRESH_COOLDOWN_MS_ESCAPED="$(escape_sed "$AUTH_REFRESH_COOLDOWN_MS")"
AUTH_REFRESH_HEADERS_ESCAPED="$(escape_sed "$AUTH_REFRESH_HEADERS")"
AUTH_PRESETS_ESCAPED="$(escape_sed "$AUTH_PRESETS")"
DEFAULT_REPO_URL_ESCAPED="$(escape_sed "$DEFAULT_REPO_URL")"
DEFAULT_REPO_DIR_ESCAPED="$(escape_sed "$DEFAULT_REPO_DIR")"
DEFAULT_REPO_BRANCH_ESCAPED="$(escape_sed "$DEFAULT_REPO_BRANCH")"
HIDE_REPO_INPUTS_ESCAPED="$(escape_sed "$HIDE_REPO_INPUTS")"
ASSET_VERSION_ESCAPED="$(escape_sed "$ASSET_VERSION")"

sed "s|__SPRITZ_API_BASE_URL__|${API_BASE_URL_ESCAPED}|g" /usr/share/nginx/html/config.js \
  | sed "s|__SPRITZ_OWNER_ID__|${OWNER_ID_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_MODE__|${AUTH_MODE_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_TOKEN_STORAGE__|${AUTH_TOKEN_STORAGE_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_TOKEN_STORAGE_KEYS__|${AUTH_TOKEN_STORAGE_KEYS_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_BEARER_TOKEN_PARAM__|${AUTH_BEARER_TOKEN_PARAM_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_PRESETS__|${AUTH_PRESETS_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_DEFAULT_REPO_URL__|${DEFAULT_REPO_URL_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_DEFAULT_REPO_DIR__|${DEFAULT_REPO_DIR_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_DEFAULT_REPO_BRANCH__|${DEFAULT_REPO_BRANCH_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_HIDE_REPO_INPUTS__|${HIDE_REPO_INPUTS_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_LOGIN_URL__|${AUTH_LOGIN_URL_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_RETURN_TO_MODE__|${AUTH_RETURN_TO_MODE_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_RETURN_TO_PARAM__|${AUTH_RETURN_TO_PARAM_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_REDIRECT_ON_UNAUTHORIZED__|${AUTH_REDIRECT_ON_UNAUTHORIZED_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_REFRESH_ENABLED__|${AUTH_REFRESH_ENABLED_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_REFRESH_URL__|${AUTH_REFRESH_URL_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_REFRESH_METHOD__|${AUTH_REFRESH_METHOD_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_REFRESH_CREDENTIALS__|${AUTH_REFRESH_CREDENTIALS_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_REFRESH_TOKEN_STORAGE_KEYS__|${AUTH_REFRESH_TOKEN_STORAGE_KEYS_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_REFRESH_TIMEOUT_MS__|${AUTH_REFRESH_TIMEOUT_MS_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_REFRESH_COOLDOWN_MS__|${AUTH_REFRESH_COOLDOWN_MS_ESCAPED}|g" \
  | sed "s|__SPRITZ_UI_AUTH_REFRESH_HEADERS__|${AUTH_REFRESH_HEADERS_ESCAPED}|g" \
  > /usr/share/nginx/html/config.runtime.js
mv /usr/share/nginx/html/config.runtime.js /usr/share/nginx/html/config.js

sed "s|__SPRITZ_UI_ASSET_VERSION__|${ASSET_VERSION_ESCAPED}|g" /usr/share/nginx/html/index.html \
  > /usr/share/nginx/html/index.runtime.html
mv /usr/share/nginx/html/index.runtime.html /usr/share/nginx/html/index.html

exec nginx -g 'daemon off;'
